version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5132:5432
    environment:
      - POSTGRES_PASSWORD=calc
      - POSTGRES_USER=calc
      - POSTGRES_DB=calc
  calc:
    ports:
      - 8080:8080
    restart: always
    build:
      dockerfile: Dockerfile
    depends_on:
      - postgres
