basePath: /
definitions:
  model.Conversion:
    properties:
      amount:
        type: number
      base:
        type: string
      quote:
        type: string
      rate:
        type: number
      value:
        type: number
    type: object
host: localhost:8080
info:
  contact: {}
  description: Calculator.
  title: Calculator
  version: "1.0"
paths:
  /api/v1/convert:
    get:
      consumes:
      - '*/*'
      description: get conversion
      parameters:
      - description: symbol base
        in: query
        maxLength: 50
        minLength: 2
        name: from
        type: string
      - description: symbol quote
        in: query
        maxLength: 50
        minLength: 2
        name: to
        type: string
      - description: amount
        in: query
        name: amount
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Conversion'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: get conversion
      tags:
      - convert
schemes:
- http
swagger: "2.0"
